# Project cat
python_sources(
    name="cat",
    sources = [
        "cat/**",
        "common/**"
    ],
    resolve="cat",
)

python_tests(
    name="cat-tests",
    sources = [
        "cat/*_test.py"
    ],
    resolve="cat",
)

# Project dog
python_sources(
    name="dog",
    sources = [
        "dog/**",
        "common/**"
    ],
    resolve="dog",
)

python_tests(
    name="dog-tests",
    sources = [
        "dog/*_test.py"
    ],
    resolve="dog",
)
