python_requirement(
    name="cat_deps",
    requirements=["pyspark==3.1.2"],
    resolve="cat_req"
)

# in this case, rikai is not actually imported
# it will appear in lockfile but will not appear in the deps of whl
python_requirement(
    name="rikai",
    requirements=["rikai==0.1.13"],
    resolve="cat_req"
)
